trigger:
- master

pool:
  name: "Leandro"

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - checkout: self

- script: |
    if (!(java -version 2>&1 | Select-String "17")) {
      choco install openjdk17 -y
    }
  displayName: 'Install Java 17 if not present'
  env:
    JAVA_HOME: 'C:\Program Files\OpenJDK\jdk-17\'
    PATH: '$(JAVA_HOME)\bin;$(PATH)'

    - script: |
        chmod +x gradlew
        ./gradlew build
      displayName: 'Build with Gradle'
      env:
        SPRING_DATASOURCE_URL: $(SPRING_DATASOURCE_URL)
        SPRING_DATASOURCE_USERNAME: $(SPRING_DATASOURCE_USERNAME)
        SPRING_DATASOURCE_PASSWORD: $(SPRING_DATASOURCE_PASSWORD)
        SPRING_JWT_SECRET: $(SPRING_JWT_SECRET)
        OPENAI_API_KEY: $(OPENAI_API_KEY)

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: './build/libs/security-0.0.1-SNAPSHOT.jar'
        ArtifactName: 'java-app'
        publishLocation: 'Container'

- stage: Deploy
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    pool: 
      name: "Leandro"
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'java-app'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureWebApp@1
            inputs:
              appName: 'wheretogofiap'
              slotName: 'Production'
              publishProfile: $(AZUREAPPSERVICE_PUBLISHPROFILE_BCA5B4788EA9434B9B9686A924042AE6)
              package: '$(System.ArtifactsDirectory)/java-app/security-0.0.1-SNAPSHOT.jar'
